Feature/feature register
JohnnatanEstevez/my-final-project pull request #1
Opened 2022-03-10 20:26 UTC by JohnnatanEstevez

Add register

2022-03-10 20:49 UTC, davidsa requested changes
Minor comments, I love the work!!

2022-03-10 20:49 UTC, davidsa commented on src/App.js
> +       */}{" "}
remove unused comment

2022-03-10 20:49 UTC, davidsa commented on src/App.js
> +          <Route path="/" element={<UserRegister />} />
Maybe rename `UserRegister` into `Register` instead. Also for UserLogin

2022-03-10 20:49 UTC, davidsa commented on src/componentes/register.js
> +  const schema = yup.object().shape({
move the schema outside the component. You could also create a directory with all schemas.

2022-03-10 20:49 UTC, davidsa commented on src/componentes/register.js
> +        console.log("1.dispatch thunk in register component");
remove console.logs

2022-03-10 20:49 UTC, davidsa commented on src/componentes/register.js
> +        //resetForm();
remove comment

2022-03-10 20:49 UTC, davidsa commented on src/componentes/register.js
> +            {/*             <img className="img-fluid w-100" src={registerImg} alt="register" />
remove comment

2022-03-10 20:49 UTC, davidsa commented on src/componentes/register.js
> +                //disabled={isSubmitting}
this comment should be uncommented, is very useful to have the button disabled when submitting

2022-03-10 20:49 UTC, davidsa commented on src/redux/index.js
> +  users: registerReducer,
change `users` into `user`

2022-03-10 20:49 UTC, davidsa commented on src/redux/index.js
> +  //window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
remove comment

2022-03-10 20:49 UTC, davidsa commented on src/redux/users/reducer.js
> +//const initialSatate = [];
remove comment

2022-03-10 20:49 UTC, davidsa commented on src/redux/users/reducer.js
> +      return [...state, action.payload]; */
remove comment

2022-03-10 20:49 UTC, davidsa commented on src/redux/users/reducer.js
> +      console.log("4.reducer SUCCESS");
remove console.log

2022-03-10 20:49 UTC, davidsa commented on src/redux/users/thunk.js
> +  };
remove console.logs

2022-03-10 20:49 UTC, davidsa commented on src/redux/users/types.js
> + */
remove commented lines

2022-03-14 15:20 UTC, JohnnatanEstevez commented on src/App.js
> +       */}{" "}
ok. done!

2022-03-14 15:20 UTC, JohnnatanEstevez commented on src/App.js
> +          <Route path="/" element={<UserRegister />} />
ok. done!

2022-03-14 15:20 UTC, JohnnatanEstevez commented on src/componentes/register.js
> +        console.log("1.dispatch thunk in register component");
ok. done!

2022-03-14 15:20 UTC, JohnnatanEstevez commented on src/componentes/register.js
> +        //resetForm();
ok. done!

2022-03-14 15:21 UTC, JohnnatanEstevez commented on src/componentes/register.js
> +            {/*             <img className="img-fluid w-100" src={registerImg} alt="register" />
ok. done!

2022-03-14 15:37 UTC, JohnnatanEstevez commented on src/componentes/register.js
> +                //disabled={isSubmitting}
ok. done!

2022-03-14 15:40 UTC, JohnnatanEstevez commented on src/redux/index.js
> +  users: registerReducer,
ok. done!

2022-03-14 15:41 UTC, JohnnatanEstevez commented on src/redux/index.js
> +  //window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
ok. done!

2022-03-14 15:41 UTC, JohnnatanEstevez commented on src/redux/users/reducer.js
> +//const initialSatate = [];
ok. done!

2022-03-14 15:42 UTC, JohnnatanEstevez commented on src/redux/users/reducer.js
> +      return [...state, action.payload]; */
ok. done!

2022-03-14 15:42 UTC, JohnnatanEstevez commented on src/redux/users/reducer.js
> +      console.log("4.reducer SUCCESS");
ok. done!

2022-03-14 15:43 UTC, JohnnatanEstevez commented on src/redux/users/thunk.js
> +  };
ok. done!

2022-03-14 15:43 UTC, JohnnatanEstevez commented on src/redux/users/types.js
> + */
ok. done!

2022-03-15 15:33 UTC, JohnnatanEstevez commented on src/componentes/register.js
> +  const schema = yup.object().shape({
Done! schema outside the component

2022-03-15 16:31 UTC, davidsa reviewed
the naming of some variables could be a little bit better

2022-03-15 16:31 UTC, davidsa commented on src/schemas/schema.js
> +export const schemaRegister = yup.object().shape({
registerSchema

2022-03-15 16:31 UTC, davidsa commented on src/schemas/schema.js
> +export const schemaLogin = yup.object().shape({
loginSchema

2022-03-15 16:31 UTC, davidsa commented on src/schemas/schema.js
> +export const schema = {
basicAuthSchema

2022-03-15 16:40 UTC, JohnnatanEstevez commented on src/schemas/schema.js
> +export const schemaRegister = yup.object().shape({
Thanks, change done!

2022-03-15 16:41 UTC, JohnnatanEstevez commented on src/schemas/schema.js
> +export const schema = {
Thanks, change done!

2022-03-15 16:41 UTC, JohnnatanEstevez commented on src/schemas/schema.js
> +export const schemaLogin = yup.object().shape({
Thanks, change done!

2022-03-15 17:08 UTC, davidsa approved these changes

2022-03-15 17:08 UTC, davidsa commented on src/componentes/register.js
> +        console.log(values);
remove console.log

2022-03-15 18:52 UTC, merged